wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1674851847.692611
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 23
      4: 3.9.13
      5: 0.13.9
      8:
      - 5
batch_size:
  desc: null
  value: 5
checkpoint_interval:
  desc: null
  value: 10
conf_thres:
  desc: null
  value: 0.1
data:
  desc: null
  value: hit.data
epochs:
  desc: null
  value: 900
evaluation_interval:
  desc: null
  value: 1
iou_thres:
  desc: null
  value: 0.5
logdir:
  desc: null
  value: yolo_logs
model:
  desc: null
  value: yolov3-custom.cfg
multiscale_training:
  desc: null
  value: false
n_cpu:
  desc: null
  value: 8
nms_thres:
  desc: null
  value: 0.5
pretrained_weights:
  desc: null
  value: null
seed:
  desc: null
  value: -1
verbose:
  desc: null
  value: false
